# Difficult-test per-integral expected outcome baseline.
#
# This file pins, for every integrand currently in the difficult-test
# corpus, the result-code each method is expected to return:
#   0 = solved and verifies symbolically against the reference antiderivative
#   1 = solved but does not symbolically match the reference (`[ fail?]`)
#   2 = engine returned the integrand unevaluated (`[ fail ]`)
#   3 = engine threw an exception (`[except]`)
#
# Bisect against the last-well-behaved baseline (commit `e4fff44`,
# pre-PR-#53) shows:
#   - Risch: 0 regressions. Every Risch fail today is a long-standing
#     domain limit (Risch only handles transcendental towers, so
#     algebraic integrands like `sqrt(...)` always return code 2;
#     QQBar-coefficient antiderivatives can fail symbolic verification
#     and end up code 1).
#   - RuleBased: 1 regression — the integrand
#     `(-1 + 4(x^5)) / ((1 + x + x^5)^2)`, tracked at
#     https://github.com/JuliaSymbolics/SymbolicIntegration.jl/issues/107
#     (rule lost during PR #53's `rule2` rewrite).
#
# Engine improvements should tighten the codes here on the same PR
# (CI fails an *unexpected pass* — a result that's better than the
# baseline declared — so this list always reflects current capability).

const DIFFICULT_BASELINE = Dict{String,Tuple{Int,Int}}(
    "2x" => (0, 0),
    "1 / (1 + x^2)" => (0, 0),
    "sin(x)" => (0, 1),
    "sqrt(1 + 2x)" => (0, 2),
    "x*sqrt(1 + 3x)" => (0, 2),
    "(x^2)*sqrt(1 + x)" => (0, 2),
    "x / sqrt(2 - 3x)" => (0, 2),
    "(1 + x) / ((2 + 2x + x^2)^3)" => (0, 0),
    "sin(x)^3" => (0, 1),
    "((-1 + z)^(1//3))*z" => (0, 2),
    "cos(x) / (sin(x)^3)" => (1, 1),
    "sqrt(4 - sin(2x))*cos(2x)" => (0, 2),
    "sin(x) / ((3 + cos(x))^2)" => (2, 1),
    "sin(x) / sqrt(cos(x)^3)" => (2, 2),
    "sin(sqrt(1 + x)) / sqrt(1 + x)" => (0, 2),
    "sin(x^n)*(x^(-1 + n))" => (2, 2),
    "(x^5) / sqrt(1 - (x^6))" => (0, 2),
    "((1 + t)^(1//4))*t" => (0, 2),
    "1 / ((1 + x^2)^(3//2))" => (0, 2),
    "(x^2)*((27 + 8(x^3))^(2//3))" => (0, 2),
    "(sin(x) + cos(x)) / ((sin(x) - cos(x))^(1//3))" => (0, 2),
    "x / sqrt(1 + x^2 + (1 + x^2)^(3//2))" => (2, 2),
    "x / (sqrt(1 + x^2)*sqrt(1 + sqrt(1 + x^2)))" => (2, 2),
    "((1 - 2x + x^2)^(1//5)) / (1 - x)" => (0, 2),
    "x*sin(x)" => (0, 0),
    "(x^2)*sin(x)" => (1, 1),
    "(x^3)*cos(x)" => (1, 1),
    "(x^3)*sin(x)" => (1, 0),
    "sin(x)*cos(x)" => (0, 1),
    "x*sin(x)*cos(x)" => (0, 1),
    "sin(x)^2" => (0, 0),
    "sin(x)^4" => (0, 1),
    "sin(x)^5" => (0, 1),
    "sin(x)^6" => (0, 1),
    "x*(sin(x)^2)" => (0, 1),
    "x*(sin(x)^3)" => (0, 1),
    "(x^2)*(sin(x)^2)" => (0, 1),
    "cos(x)^2" => (2, 0),
    "cos(x)^3" => (2, 1),
    "cos(x)^4" => (2, 1),
    "(a^2 - (x^2))^(5//2)" => (0, 2),
    "(x^5) / sqrt(5 + x^2)" => (0, 2),
    "(t^3) / ((4 + t^3)^(1//2))" => (1, 2),
    "tan(x)^2" => (0, 0),
    "tan(x)^4" => (0, 0),
    "cot(x)^2" => (2, 1),
    "cot(x)^4" => (2, 1),
    "(2 + 3x)*sin(5x)" => (0, 1),
    "x*sqrt(1 + x^2)" => (0, 2),
    "x*((-1 + x^2)^9)" => (0, 1),
    "(3 + 2x) / ((7 + 6x)^3)" => (0, 1),
    "(x^4)*((1 + x^5)^5)" => (0, 1),
    "(x^4)*((1 - x)^20)" => (0, 1),
    "sin(1 / x) / (x^2)" => (0, 1),
    "sin((-1 + x)^(1//4))" => (1, 2),
    "x*sin(x^2)*cos(x^2)" => (0, 1),
    "sqrt(1 + 3(cos(x)^2))*sin(2x)" => (2, 2),
    "1 / (2 + 3x)" => (0, 1),
    "log(x)^2" => (0, 0),
    "x*log(x)" => (0, 0),
    "x*(log(x)^2)" => (0, 0),
    "1 / (1 + t)" => (0, 0),
    "cot(x)" => (2, 1),
    "log(a*x)*(x^n)" => (0, 2),
    "(x^2)*(log(x)^2)" => (0, 0),
    "1 / (x*log(x))" => (0, 0),
    "log(1 - t) / (1 - t)" => (0, 0),
    "log(x) / (x*sqrt(1 + log(x)))" => (2, 2),
    "(x^3)*(log(x)^3)" => (0, 0),
    "(x^2)*exp(x^3)" => (0, 0),
    "(2^sqrt(x)) / sqrt(x)" => (1, 2),
    "exp(2sin(x))*cos(x)" => (2, 0),
    "sin(x)*exp(x)" => (0, 0),
    "exp(x)*cos(x)" => (0, 0),
    "1 / (1 + exp(x))" => (2, 0),
    "x*exp(x)" => (0, 0),
    "x*exp(-x)" => (1, 1),
    "(x^2)*exp(x)" => (0, 0),
    "(x^2)*exp(-2x)" => (1, 1),
    "exp(sqrt(x))" => (0, 2),
    "(x^3)*exp(-(x^2))" => (1, 1),
    "exp(a*x)*cos(b*x)" => (0, 2),
    "exp(a*x)*sin(b*x)" => (0, 2),
    "acot(x)" => (0, 2),
    "asec(x)" => (2, 2),
    "acsc(x)" => (2, 2),
    "asin(x)^2" => (2, 2),
    "asin(x) / (x^2)" => (0, 2),
    "1 / sqrt(a^2 - (x^2))" => (0, 2),
    "1 / sqrt(1 - 2x - (x^2))" => (1, 2),
    "1 / (a^2 + x^2)" => (1, 2),
    "1 / (a + b*(x^2))" => (1, 2),
    "1 / (2 - x + x^2)" => (1, 1),
    "x*atan(x)" => (0, 0),
    "(x^2)*acos(x)" => (0, 2),
    "x*(atan(x)^2)" => (2, 0),
    "atan(sqrt(x))" => (0, 2),
    "atan(sqrt(x)) / ((1 + x)*sqrt(x))" => (2, 2),
    "sqrt(1 - (x^2))" => (0, 2),
    "(x*exp(atan(x))) / ((1 + x^2)^(3//2))" => (2, 2),
    "exp(atan(x)) / ((1 + x^2)^(3//2))" => (2, 2),
    "(x^2) / ((1 + x^2)^2)" => (0, 0),
    "exp(x) / (1 + exp(2x))" => (0, 2),
    "acot(exp(x)) / exp(x)" => (2, 2),
    "((a + x) / (a - x))^(1//2)" => (2, 2),
    "sqrt((-a + x)*(b - x))" => (2, 2),
    "1 / sqrt((-a + x)*(b - x))" => (0, 2),
    "(3 + 5x) / (-3 + 2x + x^2)" => (1, 0),
    "(5 + 2x) / (-3 + 2x + x^2)" => (1, 0),
    "(3x + x^3) / (-3 - 2x + x^2)" => (2, 0),
    "(-1 + 5x + 2(x^2)) / (-2x + x^2 + x^3)" => (2, 0),
    "(3 + 2x + x^2) / ((-1 + x)*((1 + x)^2))" => (2, 0),
    "(-2 + 2x + 3(x^2)) / (-1 + x^3)" => (1, 1),
    "(2 - x + 2(x^2) - (x^3) + x^4) / ((-1 + x)*((2 + x^2)^2))" => (2, 1),
    "1 / (sin(x) + cos(x))" => (0, 1),
    "x / (4 + sqrt(4 - (x^2)) - (x^2))" => (2, 2),
    "(3 + 2x) / ((-2 + x)*(5 + x))" => (1, 1),
    "x / ((2 + x)*(3 + x)*(1 + x))" => (2, 0),
    "x / (2 - 3x + x^3)" => (2, 0),
    "(-6 + 2x + x^4) / (-2x + x^2 + x^3)" => (2, 0),
    "(7 + 8(x^3)) / ((1 + x)*((1 + 2x)^3))" => (2, 0),
    "(1 + x + 4(x^2)) / (-1 + x^3)" => (1, 0),
    "(x^4) / (4 + 5(x^2) + x^4)" => (1, 1),
    "(2 + x) / (x + x^2)" => (2, 0),
    "1 / (x*((1 + x^2)^2))" => (2, 0),
    "1 / ((1 + x)*((2 + x)^2)*((3 + x)^3))" => (2, 0),
    "x / ((1 + x)^2)" => (0, 0),
    "1 / (-x + x^3)" => (2, 0),
    "(x^2) / (-6 + x + x^2)" => (1, 0),
    "(2 + x) / (4 - 4x + x^2)" => (1, 0),
    "1 / ((5 - 4x + x^2)*(4 - 4x + x^2))" => (1, 0),
    "(-3 + x) / (2x + 3(x^2) + x^3)" => (2, 0),
    "1 / ((-1 + x^2)^2)" => (0, 1),
    "(1 + x) / (-1 + x^3)" => (0, 0),
    "(1 + x^4) / (x*((1 + x^2)^2))" => (2, 0),
    "1 / (-2(x^3) + x^4)" => (2, 0),
    "(1 - (x^3)) / (x*(1 + x^2))" => (1, 0),
    "1 / (-1 + x^4)" => (0, 1),
    "1 / (1 + x^4)" => (1, 1),
    "(x^2) / ((2 + 2x + x^2)^2)" => (0, 1),
    "(-1 + 4(x^5)) / ((1 + x + x^5)^2)" => (2, 0),
    "1 / (5 + 2sin(x) - cos(x))" => (1, 1),
    "1 / (1 + a*cos(x))" => (2, 2),
    "1 / (1 + 2cos(x))" => (2, 1),
    "1 / (1 + (1//2)*cos(x))" => (2, 1),
    "(sin(x)^2) / (1 + sin(x)^2)" => (1, 1),
    "1 / ((a^2)*(sin(x)^2) + (b^2)*(cos(x)^2))" => (2, 2),
    "1 / ((a*sin(x) + b*cos(x))^2)" => (0, 2),
    "sin(x) / (1 + sin(x) + cos(x))" => (1, 1),
    "sqrt(3 - (x^2))" => (0, 2),
    "x / sqrt(3 - (x^2))" => (0, 2),
    "sqrt(3 - (x^2)) / x" => (1, 2),
    "sqrt(x + x^2) / x" => (0, 2),
    "sqrt(5 + x^2)" => (0, 2),
    "x / sqrt(1 + x + x^2)" => (1, 2),
    "1 / sqrt(x + x^2)" => (0, 2),
    "sqrt(2 - x - (x^2)) / (x^2)" => (1, 2),
    "log(t) / (1 + t)" => (0, 2),
    "log(exp(cos(x)))" => (0, 2),
    "exp(t) / t" => (0, 2),
    "exp(a*t) / t" => (0, 2),
    "exp(t) / (t^2)" => (0, 2),
    "exp(1 / t)" => (0, 2),
    "1 / ((-1 - a + t)*exp(t))" => (2, 2),
    "(t*exp(t^2)) / (1 + t^2)" => (2, 2),
    "exp(t) / ((1 + t)^2)" => (0, 2),
    "log(1 + t)*exp(t)" => (2, 2),
    "t / exp(t)" => (1, 1),
    "(t^2) / exp(t)" => (1, 0),
    "(t^3) / exp(t)" => (1, 0),
    "(c*sin(x) + d*cos(x)) / (a*sin(x) + b*cos(x))" => (0, 2),
    "1 / log(t)" => (0, 2),
    "1 / (log(t)^2)" => (0, 2),
    "exp(2t) / (-1 + t)" => (0, 2),
    "exp(2x) / (2 - 3x + x^2)" => (2, 2),
    "1 / ((1 + t^3)^(1//2))" => (0, 2),
)
