# (* ::Subsection::Closed:: *) 
# (* 1.1.1.2 (a+b x)^m (c+d x)^n *) 
rule1_1_1_1_1 = @rule ∫(((~a) + (~!b)*(x))^(~!m)*((~c) + (~!d)*(x))) => !contains_x((~a), (~b), (~c), (~d), (~m)) && isequal((~a)*(~d) - (~b)*(~c)*((~m) + 2), 0) ? (~d)*x*((~a) + (~b)*x)^((~m) + 1)/((~b)*((~m) + 2)) : nothing
rule1_1_1_1_2 = @rule ∫(1/(((~a) + (~!b)*(x))*((~c) + (~!d)*(x)))) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) ? Int(1/((~a)*(~c) + (~b)*(~d)*x^2), x) : nothing
rule1_1_1_1_3 = @rule ∫(1/(((~!a) + (~!b)*(x))*((~!c) + (~!d)*(x)))) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) ? (~b)/((~b)*(~c) - (~a)*(~d))*Int(1/((~a) + (~b)*x), x) - (~d)/((~b)*(~c) - (~a)*(~d))*Int(1/((~c) + (~d)*x), x) : nothing
rule1_1_1_1_4 = @rule ∫(((~!a) + (~!b)*(x))^(~!m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && isequal((~m) + (~n) + 2, 0) && !isequal((~m), -1) ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) : nothing
rule1_1_1_1_5 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~m)) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && is_greater_than((~m) + 1/2, 0) ? x*((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~m)/(2*(~m) + 1) + 2*(~a)*(~c)*(~m)/(2*(~m) + 1)*Int(((~a) + (~b)*x)^((~m) - 1)*((~c) + (~d)*x)^((~m) - 1), x) : nothing
rule1_1_1_1_6 = @rule ∫(1/(((~a) + (~!b)*(x))^(3/2)*((~c) + (~!d)*(x))^(3/2))) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) ? x/((~a)*(~c)*sqrt((~a) + (~b)*x)*sqrt((~c) + (~d)*x)) : nothing
rule1_1_1_1_7 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~m)) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && ILtQ[(~m) + 3/2, 0] ? -x*((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~m) + 1)/(2*(~a)*(~c)*((~m) + 1)) + (2*(~m) + 3)/(2*(~a)*(~c)*((~m) + 1))* Int(((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~m) + 1), x) : nothing
rule1_1_1_1_8 = @rule ∫(((~a) + (~!b)*(x))^(~!m)*((~c) + (~!d)*(x))^(~!m)) => !contains_x((~a), (~b), (~c), (~d), (~m)) && isequal((~b)*(~c) + (~a)*(~d), 0) && (IntegerQ[(~m)] || GtQ[(~a), 0] && GtQ[(~c), 0]) ? Int(((~a)*(~c) + (~b)*(~d)*x^2)^(~m), x) : nothing
rule1_1_1_1_9 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~m)) => !contains_x((~a), (~b), (~c), (~d), (~m)) && isequal((~b)*(~c) + (~a)*(~d), 0) && Not[IntegerQ[2*(~m)]] ? ((~a) + (~b)*x)^ FracPart((~m))*((~c) + (~d)*x)^FracPart((~m))/((~a)*(~c) + (~b)*(~d)*x^2)^FracPart((~m))* Int(((~a)*(~c) + (~b)*(~d)*x^2)^(~m), x) : nothing
rule1_1_1_1_10 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), -1] && Not[IntegerQ[(~n)]] && GtQ[(~n), 0] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n)/((~b)*((~m) + 1)) - (~d)*(~n)/((~b)*((~m) + 1))*Int(((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) - 1), x) : nothing
rule1_1_1_1_11 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), -1] && Not[IntegerQ[(~n)]] && LtQ[(~n), 0] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n), x) : nothing
rule1_1_1_1_12 = @rule ∫(((~!a) + (~!b)*(x))^(~!m)*((~!c) + (~!d)*(x))^(~!n)) => !contains_x((~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && is_greater_than((~m), 0) && (Not[IntegerQ[(~n)]] || isequal((~c), 0) && LeQ[7*(~m) + 4*(~n) + 4, 0] || LtQ[9*(~m) + 5*((~n) + 1), 0] || GtQ[(~m) + (~n) + 2, 0]) ? Int(ExpandIntegrand(((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~n), x), x) : nothing
rule1_1_1_1_13 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~!n)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), 0] && IntegerQ[(~n)] && Not[is_greater_than((~n), 0) && LtQ[(~m) + (~n) + 2, 0]] ? Int(ExpandIntegrand(((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~n), x), x) : nothing
rule1_1_1_1_14 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[Simplify[(~m) + (~n) + 2], 0] && !isequal((~m), -1) && Not[ LtQ[(~m), -1] && LtQ[(~n), -1] && (isequal((~a), 0) || !isequal((~c), 0) && LtQ[(~m) - (~n), 0] && IntegerQ[(~n)])] && (SumSimplerQ[(~m), 1] || Not[SumSimplerQ[(~n), 1]]) ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*Simplify((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*x)^Simplify((~m) + 1)*((~c) + (~d)*x)^(~n), x) : nothing
rule1_1_1_1_15 = @rule ∫(1/(((~a) + (~!b)*(x))^(9/4)*((~c) + (~!d)*(x))^(1/4))) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && NegQ[(~a)^2*(~b)^2] ? -4/(5*(~b)*((~a) + (~b)*x)^(5/4)*((~c) + (~d)*x)^(1/4)) - (~d)/(5*(~b))*Int(1/(((~a) + (~b)*x)^(5/4)*((~c) + (~d)*x)^(5/4)), x) : nothing
rule1_1_1_1_16 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && GtQ[(~n), 0] && LtQ[(~m), -1] && Not[IntegerQ[(~n)] && Not[IntegerQ[(~m)]]] && Not[ ILeQ[(~m) + (~n) + 2, 0] && (FractionQ[(~m)] || GeQ[2*(~n) + (~m) + 1, 0])] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n)/((~b)*((~m) + 1)) - (~d)*(~n)/((~b)*((~m) + 1))*Int(((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) - 1), x) : nothing
rule1_1_1_1_17 = @rule ∫(1/(((~a) + (~!b)*(x))^(5/4)*((~c) + (~!d)*(x))^(1/4))) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && NegQ[(~a)^2*(~b)^2] ? -2/((~b)*((~a) + (~b)*x)^(1/4)*((~c) + (~d)*x)^(1/4)) + (~c)*Int(1/(((~a) + (~b)*x)^(5/4)*((~c) + (~d)*x)^(5/4)), x) : nothing
rule1_1_1_1_18 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && is_greater_than((~m) + 1/2, 0) && is_greater_than((~n) + 1/2, 0) && LtQ[(~m), (~n)] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n)/((~b)*((~m) + (~n) + 1)) + 2*(~c)*(~n)/((~m) + (~n) + 1)*Int(((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^((~n) - 1), x) : nothing
rule1_1_1_1_19 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && GtQ[(~n), 0] && !isequal((~m) + (~n) + 1, 0) && Not[ is_greater_than((~m), 0) && (Not[IntegerQ[(~n)]] || GtQ[(~m), 0] && LtQ[(~m) - (~n), 0])] && Not[ILtQ[(~m) + (~n) + 2, 0]] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n)/((~b)*((~m) + (~n) + 1)) + (~n)*((~b)*(~c) - (~a)*(~d))/((~b)*((~m) + (~n) + 1))* Int(((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^((~n) - 1), x) : nothing
rule1_1_1_1_20 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[(~m), -1] && Not[ LtQ[(~n), -1] && (isequal((~a), 0) || !isequal((~c), 0) && LtQ[(~m) - (~n), 0] && IntegerQ[(~n)])] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*x)^((~m) + 1)*((~c) + (~d)*x)^(~n), x) : nothing
rule1_1_1_1_21 = @rule ∫(1/(Sqrt[(~a) + (~!b)*(x)]*Sqrt[(~c) + (~!d)*(x)])) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~a) + (~c), 0) && isequal((~b) - (~d), 0) && GtQ[(~a), 0] ? ArcCosh((~b)*x/(~a))/(~b) : nothing
rule1_1_1_1_22 = @rule ∫(1/(Sqrt[(~a) + (~!b)*(x)]*Sqrt[(~!c) + (~!d)*(x)])) => !contains_x((~a), (~b), (~c), (~d)) && isequal((~b) + (~d), 0) && GtQ[(~a) + (~c), 0] ? Int(1/sqrt((~a)*(~c) - (~b)*((~a) - (~c))*x - (~b)^2*x^2), x) : nothing
rule1_1_1_1_23 = @rule ∫(1/(Sqrt[(~!a) + (~!b)*(x)]*Sqrt[(~!c) + (~!d)*(x)])) => !contains_x((~a), (~b), (~c), (~d)) && GtQ[(~b)*(~c) - (~a)*(~d), 0] && GtQ[(~b), 0] ? 2/sqrt((~b))* Subst(Int(1/sqrt((~b)*(~c) - (~a)*(~d) + (~d)*x^2), x), x, sqrt((~a) + (~b)*x)) : nothing
rule1_1_1_1_24 = @rule ∫(1/(((~!a) + (~!b)*(x))*((~!c) + (~!d)*(x))^(1/3))) => !contains_x((~a), (~b), (~c), (~d)) && PosQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*x))/(2*(~b)*(~q)) - 3/(2*(~b)*(~q))*Subst(Int(1/((~q) - x), x), x, ((~c) + (~d)*x)^(1/3)) + 3/(2*(~b))* Subst(Int(1/((~q)^2 + (~q)*x + x^2), x), x, ((~c) + (~d)*x)^(1/3))) : nothing
rule1_1_1_1_25 = @rule ∫(1/(((~!a) + (~!b)*(x))*((~!c) + (~!d)*(x))^(1/3))) => !contains_x((~a), (~b), (~c), (~d)) && NegQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(-((~b)*(~c) - (~a)*(~d))/(~b), 3)}, log(((~a) + (~b)*x))/(2*(~b)*(~q)) - 3/(2*(~b)*(~q))*Subst(Int(1/((~q) + x), x), x, ((~c) + (~d)*x)^(1/3)) + 3/(2*(~b))* Subst(Int(1/((~q)^2 - (~q)*x + x^2), x), x, ((~c) + (~d)*x)^(1/3))) : nothing
rule1_1_1_1_26 = @rule ∫(1/(((~!a) + (~!b)*(x))*((~!c) + (~!d)*(x))^(2/3))) => !contains_x((~a), (~b), (~c), (~d)) && PosQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*x))/(2*(~b)*(~q)^2) - 3/(2*(~b)*(~q)^2)*Subst(Int(1/((~q) - x), x), x, ((~c) + (~d)*x)^(1/3)) - 3/(2*(~b)*(~q))* Subst(Int(1/((~q)^2 + (~q)*x + x^2), x), x, ((~c) + (~d)*x)^(1/3))) : nothing
rule1_1_1_1_27 = @rule ∫(1/(((~!a) + (~!b)*(x))*((~!c) + (~!d)*(x))^(2/3))) => !contains_x((~a), (~b), (~c), (~d)) && NegQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(-((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*x))/(2*(~b)*(~q)^2) + 3/(2*(~b)*(~q)^2)*Subst(Int(1/((~q) + x), x), x, ((~c) + (~d)*x)^(1/3)) + 3/(2*(~b)*(~q))* Subst(Int(1/((~q)^2 - (~q)*x + x^2), x), x, ((~c) + (~d)*x)^(1/3))) : nothing
rule1_1_1_1_28 = @rule ∫(1/(((~!a) + (~!b)*(x))^(1/3)*((~!c) + (~!d)*(x))^(2/3))) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && PosQ[(~d)/(~b)] ? With({(~q) = Rt((~d)/(~b), 3)}, -sqrt(3)*(~q)/(~d)* ArcTan(2*(~q)*((~a) + (~b)*x)^(1/3)/(sqrt(3)*((~c) + (~d)*x)^(1/3)) + 1/sqrt(3)) - (~q)/(2*(~d))*log((~c) + (~d)*x) - 3*(~q)/(2*(~d))*log((~q)*((~a) + (~b)*x)^(1/3)/((~c) + (~d)*x)^(1/3) - 1)) : nothing
rule1_1_1_1_29 = @rule ∫(1/(((~!a) + (~!b)*(x))^(1/3)*((~!c) + (~!d)*(x))^(2/3))) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && NegQ[(~d)/(~b)] ? With({(~q) = Rt(-(~d)/(~b), 3)}, sqrt(3)*(~q)/(~d)* ArcTan(1/sqrt(3) - 2*(~q)*((~a) + (~b)*x)^(1/3)/(sqrt(3)*((~c) + (~d)*x)^(1/3))) + (~q)/(2*(~d))*log((~c) + (~d)*x) + 3*(~q)/(2*(~d))*log((~q)*((~a) + (~b)*x)^(1/3)/((~c) + (~d)*x)^(1/3) + 1)) : nothing
rule1_1_1_1_30 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~m)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[3, Denominator[(~m)], 4] && AtomQ[(~b)*(~c) + (~a)*(~d)] ? ((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~m)/((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*x + (~b)*(~d)*x^2)^(~m)* Int(((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*x + (~b)*(~d)*x^2)^(~m), x) : nothing
rule1_1_1_1_31 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~m)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[3, Denominator[(~m)], 4] ? ((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~m)/(((~a) + (~b)*x)*((~c) + (~d)*x))^(~m)* Int(((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*x + (~b)*(~d)*x^2)^(~m), x) : nothing
rule1_1_1_1_32 = @rule ∫(((~!a) + (~!b)*(x))^(~m)*((~!c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[-1, (~n), 0] && LeQ[Denominator[(~n)], Denominator[(~m)]] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? With({(~p) = Denominator((~m))}, (~p)/(~b)* Subst(Int(x^((~p)*((~m) + 1) - 1)*((~c) - (~a)*(~d)/(~b) + (~d)*x^(~p)/(~b))^(~n), x), x, ((~a) + (~b)*x)^(1/(~p)))) : nothing
rule1_1_1_1_33 = @rule ∫(((~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && (IntegerQ[(~n)] || GtQ[(~c), 0] && Not[isequal((~n), -1/2) && isequal((~c)^2 - (~d)^2, 0) && GtQ[-(~d)/((~b)*(~c)), 0]]) ? (~c)^(~n)*((~b)*x)^((~m) + 1)/((~b)*((~m) + 1))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*x/(~c)) : nothing
rule1_1_1_1_34 = @rule ∫(((~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~n)]] && (IntegerQ[(~m)] || GtQ[-(~d)/((~b)*(~c)), 0]) ? ((~c) + (~d)*x)^((~n) + 1)/((~d)*((~n) + 1)*(-(~d)/((~b)*(~c)))^(~m))* Hypergeometric2F1(-(~m), (~n) + 1, (~n) + 2, 1 + (~d)*x/(~c)) : nothing
rule1_1_1_1_35 = @rule ∫(((~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && Not[GtQ[(~c), 0]] && Not[GtQ[-(~d)/((~b)*(~c)), 0]] && (RationalQ[(~m)] && Not[isequal((~n), -1/2) && isequal((~c)^2 - (~d)^2, 0]] || Not[RationalQ[(~n)])) ? (~c)^IntPart((~n))*((~c) + (~d)*x)^FracPart((~n))/(1 + (~d)*x/(~c))^FracPart((~n))* Int(((~b)*x)^(~m)*(1 + (~d)*x/(~c))^(~n), x) : nothing
rule1_1_1_1_36 = @rule ∫(((~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && Not[GtQ[(~c), 0]] && Not[GtQ[-(~d)/((~b)*(~c)), 0]] ? (-(~b)*(~c)/(~d))^IntPart((~m))*((~b)*x)^FracPart((~m))/(-(~d)*x/(~c))^FracPart((~m))* Int((-(~d)*x/(~c))^(~m)*((~c) + (~d)*x)^(~n), x) : nothing
rule1_1_1_1_37 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~m)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && IntegerQ[(~n)] ? ((~b)*(~c) - (~a)*(~d))^(~n)*((~a) + (~b)*x)^((~m) + 1)/((~b)^((~n) + 1)*((~m) + 1))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*((~a) + (~b)*x)/((~b)*(~c) - (~a)*(~d))) : nothing
rule1_1_1_1_38 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && GtQ[(~b)/((~b)*(~c) - (~a)*(~d)), 0] && (RationalQ[(~m)] || Not[RationalQ[(~n)] && GtQ[-(~d)/((~b)*(~c) - (~a)*(~d)), 0]]) ? ((~a) + (~b)*x)^((~m) + 1)/((~b)*((~m) + 1)*((~b)/((~b)*(~c) - (~a)*(~d)))^(~n))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*((~a) + (~b)*x)/((~b)*(~c) - (~a)*(~d))) : nothing
rule1_1_1_1_39 = @rule ∫(((~a) + (~!b)*(x))^(~m)*((~c) + (~!d)*(x))^(~n)) => !contains_x((~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && (RationalQ[(~m)] || Not[SimplerQ[(~n) + 1, (~m) + 1]]) ? ((~c) + (~d)*x)^ FracPart( (~n))/(((~b)/((~b)*(~c) - (~a)*(~d)))^IntPart((~n))*((~b)*((~c) + (~d)*x)/((~b)*(~c) - (~a)*(~d)))^ FracPart((~n)))* Int(((~a) + (~b)*x)^(~m)*Simp((~b)*(~c)/((~b)*(~c) - (~a)*(~d)) + (~b)*(~d)*x/((~b)*(~c) - (~a)*(~d)), x)^(~n), x) : nothing
rule1_1_1_1_40 = @rule ∫(((~!a) + (~!b)*(~u))^(~!m)*((~!c) + (~!d)*(~u))^(~!n)) => !contains_x((~a), (~b), (~c), (~d), (~m), (~n)) && linear_expansion((~u), x)[3] && !isequal(Coefficient[(~u), x, 0], 0) ? 1/Coefficient((~u), x, 1)* Subst(Int(((~a) + (~b)*x)^(~m)*((~c) + (~d)*x)^(~n), x), x, (~u)) : nothing
# (* IntLinearQ[a,b,c,d,m,n,x] returns True iff (a+b*x)^m*(c+d*x)^n is  integrable wrt x in terms of non-hypergeometric functions. *) IntLinearQ[a_, b_, c_, d_, m_, n_, x_] := IGtQ[m, 0] || IGtQ[n, 0] || IntegersQ[3*m, 3*n] || IntegersQ[4*m, 4*n] || IntegersQ[2*m, 6*n] || IntegersQ[6*m, 2*n] || ILtQ[m + n, -1] || IntegerQ[m + n] && RationalQ[m] 
