file_rules = [
# (* ::Subsection::Closed:: *) 
# (* 1.1.1.2 (a+b x)^m (c+d x)^n *) 
    :(@rule ∫(((~a) + (~!b)*(~v))^(~!m)*((~c) + (~!d)*(~v)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m)) && isequal((~a)*(~d) - (~b)*(~c)*((~m) + 2), 0) ? (~d)*(~v)*((~a) + (~b)*(~v))^((~m) + 1)/((~b)*((~m) + 2)) : nothing) #1_1_1_2_1
#     :(@rule ∫(1/(((~a) + (~!b)*(~v))*((~c) + (~!d)*(~v))),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) ? Int(1/((~a)*(~c) + (~b)*(~d)*(~v)^2), (~v)) : nothing) #1_1_1_2_2
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))*((~!c) + (~!d)*(~v))),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) ? (~b)/((~b)*(~c) - (~a)*(~d))*Int(1/((~a) + (~b)*(~v)), (~v)) - (~d)/((~b)*(~c) - (~a)*(~d))*Int(1/((~c) + (~d)*(~v)), (~v)) : nothing) #1_1_1_2_3
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~!m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && isequal((~m) + (~n) + 2, 0) && !isequal((~m), -1) ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) : nothing) #1_1_1_2_4
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && is_greater_than((~m) + 1/2, 0) ? (~v)*((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~m)/(2*(~m) + 1) + 2*(~a)*(~c)*(~m)/(2*(~m) + 1)*Int(((~a) + (~b)*(~v))^((~m) - 1)*((~c) + (~d)*(~v))^((~m) - 1), (~v)) : nothing) #1_1_1_2_5
#     :(@rule ∫(1/(((~a) + (~!b)*(~v))^(3/2)*((~c) + (~!d)*(~v))^(3/2)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) ? (~v)/((~a)*(~c)*sqrt((~a) + (~b)*(~v))*sqrt((~c) + (~d)*(~v))) : nothing) #1_1_1_2_6
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && ILtQ[(~m) + 3/2, 0] ? -(~v)*((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~m) + 1)/(2*(~a)*(~c)*((~m) + 1)) + (2*(~m) + 3)/(2*(~a)*(~c)*((~m) + 1))* Int(((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~m) + 1), (~v)) : nothing) #1_1_1_2_7
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~!m)*((~c) + (~!d)*(~v))^(~!m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m)) && isequal((~b)*(~c) + (~a)*(~d), 0) && (IntegerQ[(~m)] || GtQ[(~a), 0] && GtQ[(~c), 0]) ? Int(((~a)*(~c) + (~b)*(~d)*(~v)^2)^(~m), (~v)) : nothing) #1_1_1_2_8
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m)) && isequal((~b)*(~c) + (~a)*(~d), 0) && Not[IntegerQ[2*(~m)]] ? ((~a) + (~b)*(~v))^ FracPart((~m))*((~c) + (~d)*(~v))^FracPart((~m))/((~a)*(~c) + (~b)*(~d)*(~v)^2)^FracPart((~m))* Int(((~a)*(~c) + (~b)*(~d)*(~v)^2)^(~m), (~v)) : nothing) #1_1_1_2_9
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), -1] && Not[IntegerQ[(~n)]] && GtQ[(~n), 0] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n)/((~b)*((~m) + 1)) - (~d)*(~n)/((~b)*((~m) + 1))*Int(((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) - 1), (~v)) : nothing) #1_1_1_2_10
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), -1] && Not[IntegerQ[(~n)]] && LtQ[(~n), 0] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n), (~v)) : nothing) #1_1_1_2_11
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~!m)*((~!c) + (~!d)*(~v))^(~!n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && is_greater_than((~m), 0) && (Not[IntegerQ[(~n)]] || isequal((~c), 0) && LeQ[7*(~m) + 4*(~n) + 4, 0] || LtQ[9*(~m) + 5*((~n) + 1), 0] || GtQ[(~m) + (~n) + 2, 0]) ? Int(E(~v)pandIntegrand(((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~n), (~v)), (~v)) : nothing) #1_1_1_2_12
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~!n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[(~m), 0] && IntegerQ[(~n)] && Not[is_greater_than((~n), 0) && LtQ[(~m) + (~n) + 2, 0]] ? Int(E(~v)pandIntegrand(((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~n), (~v)), (~v)) : nothing) #1_1_1_2_13
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && ILtQ[Simplify[(~m) + (~n) + 2], 0] && !isequal((~m), -1) && Not[ LtQ[(~m), -1] && LtQ[(~n), -1] && (isequal((~a), 0) || !isequal((~c), 0) && LtQ[(~m) - (~n), 0] && IntegerQ[(~n)])] && (SumSimplerQ[(~m), 1] || Not[SumSimplerQ[(~n), 1]]) ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*Simplify((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*(~v))^Simplify((~m) + 1)*((~c) + (~d)*(~v))^(~n), (~v)) : nothing) #1_1_1_2_14
#     :(@rule ∫(1/(((~a) + (~!b)*(~v))^(9/4)*((~c) + (~!d)*(~v))^(1/4)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && NegQ[(~a)^2*(~b)^2] ? -4/(5*(~b)*((~a) + (~b)*(~v))^(5/4)*((~c) + (~d)*(~v))^(1/4)) - (~d)/(5*(~b))*Int(1/(((~a) + (~b)*(~v))^(5/4)*((~c) + (~d)*(~v))^(5/4)), (~v)) : nothing) #1_1_1_2_15
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && GtQ[(~n), 0] && LtQ[(~m), -1] && Not[IntegerQ[(~n)] && Not[IntegerQ[(~m)]]] && Not[ ILeQ[(~m) + (~n) + 2, 0] && (FractionQ[(~m)] || GeQ[2*(~n) + (~m) + 1, 0])] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n)/((~b)*((~m) + 1)) - (~d)*(~n)/((~b)*((~m) + 1))*Int(((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) - 1), (~v)) : nothing) #1_1_1_2_16
#     :(@rule ∫(1/(((~a) + (~!b)*(~v))^(5/4)*((~c) + (~!d)*(~v))^(1/4)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && NegQ[(~a)^2*(~b)^2] ? -2/((~b)*((~a) + (~b)*(~v))^(1/4)*((~c) + (~d)*(~v))^(1/4)) + (~c)*Int(1/(((~a) + (~b)*(~v))^(5/4)*((~c) + (~d)*(~v))^(5/4)), (~v)) : nothing) #1_1_1_2_17
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b)*(~c) + (~a)*(~d), 0) && is_greater_than((~m) + 1/2, 0) && is_greater_than((~n) + 1/2, 0) && LtQ[(~m), (~n)] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n)/((~b)*((~m) + (~n) + 1)) + 2*(~c)*(~n)/((~m) + (~n) + 1)*Int(((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^((~n) - 1), (~v)) : nothing) #1_1_1_2_18
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && GtQ[(~n), 0] && !isequal((~m) + (~n) + 1, 0) && Not[ is_greater_than((~m), 0) && (Not[IntegerQ[(~n)]] || GtQ[(~m), 0] && LtQ[(~m) - (~n), 0])] && Not[ILtQ[(~m) + (~n) + 2, 0]] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n)/((~b)*((~m) + (~n) + 1)) + (~n)*((~b)*(~c) - (~a)*(~d))/((~b)*((~m) + (~n) + 1))* Int(((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^((~n) - 1), (~v)) : nothing) #1_1_1_2_19
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[(~m), -1] && Not[ LtQ[(~n), -1] && (isequal((~a), 0) || !isequal((~c), 0) && LtQ[(~m) - (~n), 0] && IntegerQ[(~n)])] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? ((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^((~n) + 1)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1)) - (~d)*((~m) + (~n) + 2)/(((~b)*(~c) - (~a)*(~d))*((~m) + 1))* Int(((~a) + (~b)*(~v))^((~m) + 1)*((~c) + (~d)*(~v))^(~n), (~v)) : nothing) #1_1_1_2_20
#     :(@rule ∫(1/(Sqrt[(~a) + (~!b)*(~v)]*Sqrt[(~c) + (~!d)*(~v)]),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~a) + (~c), 0) && isequal((~b) - (~d), 0) && GtQ[(~a), 0] ? ArcCosh((~b)*(~v)/(~a))/(~b) : nothing) #1_1_1_2_21
#     :(@rule ∫(1/(Sqrt[(~a) + (~!b)*(~v)]*Sqrt[(~!c) + (~!d)*(~v)]),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && isequal((~b) + (~d), 0) && GtQ[(~a) + (~c), 0] ? Int(1/sqrt((~a)*(~c) - (~b)*((~a) - (~c))*(~v) - (~b)^2*(~v)^2), (~v)) : nothing) #1_1_1_2_22
#     :(@rule ∫(1/(Sqrt[(~!a) + (~!b)*(~v)]*Sqrt[(~!c) + (~!d)*(~v)]),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && GtQ[(~b)*(~c) - (~a)*(~d), 0] && GtQ[(~b), 0] ? 2/sqrt((~b))* Subst(Int(1/sqrt((~b)*(~c) - (~a)*(~d) + (~d)*(~v)^2), (~v)), (~v), sqrt((~a) + (~b)*(~v))) : nothing) #1_1_1_2_23
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))*((~!c) + (~!d)*(~v))^(1/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && PosQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*(~v)))/(2*(~b)*(~q)) - 3/(2*(~b)*(~q))*Subst(Int(1/((~q) - (~v)), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3)) + 3/(2*(~b))* Subst(Int(1/((~q)^2 + (~q)*(~v) + (~v)^2), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3))) : nothing) #1_1_1_2_24
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))*((~!c) + (~!d)*(~v))^(1/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && NegQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(-((~b)*(~c) - (~a)*(~d))/(~b), 3)}, log(((~a) + (~b)*(~v)))/(2*(~b)*(~q)) - 3/(2*(~b)*(~q))*Subst(Int(1/((~q) + (~v)), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3)) + 3/(2*(~b))* Subst(Int(1/((~q)^2 - (~q)*(~v) + (~v)^2), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3))) : nothing) #1_1_1_2_25
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))*((~!c) + (~!d)*(~v))^(2/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && PosQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*(~v)))/(2*(~b)*(~q)^2) - 3/(2*(~b)*(~q)^2)*Subst(Int(1/((~q) - (~v)), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3)) - 3/(2*(~b)*(~q))* Subst(Int(1/((~q)^2 + (~q)*(~v) + (~v)^2), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3))) : nothing) #1_1_1_2_26
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))*((~!c) + (~!d)*(~v))^(2/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && NegQ[((~b)*(~c) - (~a)*(~d))/(~b)] ? With({(~q) = Rt(-((~b)*(~c) - (~a)*(~d))/(~b), 3)}, -log(((~a) + (~b)*(~v)))/(2*(~b)*(~q)^2) + 3/(2*(~b)*(~q)^2)*Subst(Int(1/((~q) + (~v)), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3)) + 3/(2*(~b)*(~q))* Subst(Int(1/((~q)^2 - (~q)*(~v) + (~v)^2), (~v)), (~v), ((~c) + (~d)*(~v))^(1/3))) : nothing) #1_1_1_2_27
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))^(1/3)*((~!c) + (~!d)*(~v))^(2/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && PosQ[(~d)/(~b)] ? With({(~q) = Rt((~d)/(~b), 3)}, -sqrt(3)*(~q)/(~d)* ArcTan(2*(~q)*((~a) + (~b)*(~v))^(1/3)/(sqrt(3)*((~c) + (~d)*(~v))^(1/3)) + 1/sqrt(3)) - (~q)/(2*(~d))*log((~c) + (~d)*(~v)) - 3*(~q)/(2*(~d))*log((~q)*((~a) + (~b)*(~v))^(1/3)/((~c) + (~d)*(~v))^(1/3) - 1)) : nothing) #1_1_1_2_28
#     :(@rule ∫(1/(((~!a) + (~!b)*(~v))^(1/3)*((~!c) + (~!d)*(~v))^(2/3)),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && NegQ[(~d)/(~b)] ? With({(~q) = Rt(-(~d)/(~b), 3)}, sqrt(3)*(~q)/(~d)* ArcTan(1/sqrt(3) - 2*(~q)*((~a) + (~b)*(~v))^(1/3)/(sqrt(3)*((~c) + (~d)*(~v))^(1/3))) + (~q)/(2*(~d))*log((~c) + (~d)*(~v)) + 3*(~q)/(2*(~d))*log((~q)*((~a) + (~b)*(~v))^(1/3)/((~c) + (~d)*(~v))^(1/3) + 1)) : nothing) #1_1_1_2_29
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[3, Denominator[(~m)], 4] && AtomQ[(~b)*(~c) + (~a)*(~d)] ? ((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~m)/((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*(~v) + (~b)*(~d)*(~v)^2)^(~m)* Int(((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*(~v) + (~b)*(~d)*(~v)^2)^(~m), (~v)) : nothing) #1_1_1_2_30
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~m),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[3, Denominator[(~m)], 4] ? ((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~m)/(((~a) + (~b)*(~v))*((~c) + (~d)*(~v)))^(~m)* Int(((~a)*(~c) + ((~b)*(~c) + (~a)*(~d))*(~v) + (~b)*(~d)*(~v)^2)^(~m), (~v)) : nothing) #1_1_1_2_31
#     :(@rule ∫(((~!a) + (~!b)*(~v))^(~m)*((~!c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && LtQ[-1, (~m), 0] && LeQ[-1, (~n), 0] && LeQ[Denominator[(~n)], Denominator[(~m)]] && Intlinear_expansion((~a), (~b), (~c), (~d), (~m), (~n), x)[3] ? With({(~p) = Denominator((~m))}, (~p)/(~b)* Subst(Int((~v)^((~p)*((~m) + 1) - 1)*((~c) - (~a)*(~d)/(~b) + (~d)*(~v)^(~p)/(~b))^(~n), (~v)), (~v), ((~a) + (~b)*(~v))^(1/(~p)))) : nothing) #1_1_1_2_32
#     :(@rule ∫(((~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && (IntegerQ[(~n)] || GtQ[(~c), 0] && Not[isequal((~n), -1/2) && isequal((~c)^2 - (~d)^2, 0) && GtQ[-(~d)/((~b)*(~c)), 0]]) ? (~c)^(~n)*((~b)*(~v))^((~m) + 1)/((~b)*((~m) + 1))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*(~v)/(~c)) : nothing) #1_1_1_2_33
#     :(@rule ∫(((~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~n)]] && (IntegerQ[(~m)] || GtQ[-(~d)/((~b)*(~c)), 0]) ? ((~c) + (~d)*(~v))^((~n) + 1)/((~d)*((~n) + 1)*(-(~d)/((~b)*(~c)))^(~m))* Hypergeometric2F1(-(~m), (~n) + 1, (~n) + 2, 1 + (~d)*(~v)/(~c)) : nothing) #1_1_1_2_34
#     :(@rule ∫(((~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && Not[GtQ[(~c), 0]] && Not[GtQ[-(~d)/((~b)*(~c)), 0]] && (RationalQ[(~m)] && Not[isequal((~n), -1/2) && isequal((~c)^2 - (~d)^2, 0]] || Not[RationalQ[(~n)])) ? (~c)^IntPart((~n))*((~c) + (~d)*(~v))^FracPart((~n))/(1 + (~d)*(~v)/(~c))^FracPart((~n))* Int(((~b)*(~v))^(~m)*(1 + (~d)*(~v)/(~c))^(~n), (~v)) : nothing) #1_1_1_2_35
#     :(@rule ∫(((~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~b), (~c), (~d), (~m), (~n)) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && Not[GtQ[(~c), 0]] && Not[GtQ[-(~d)/((~b)*(~c)), 0]] ? (-(~b)*(~c)/(~d))^IntPart((~m))*((~b)*(~v))^FracPart((~m))/(-(~d)*(~v)/(~c))^FracPart((~m))* Int((-(~d)*(~v)/(~c))^(~m)*((~c) + (~d)*(~v))^(~n), (~v)) : nothing) #1_1_1_2_36
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && IntegerQ[(~n)] ? ((~b)*(~c) - (~a)*(~d))^(~n)*((~a) + (~b)*(~v))^((~m) + 1)/((~b)^((~n) + 1)*((~m) + 1))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*((~a) + (~b)*(~v))/((~b)*(~c) - (~a)*(~d))) : nothing) #1_1_1_2_37
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && GtQ[(~b)/((~b)*(~c) - (~a)*(~d)), 0] && (RationalQ[(~m)] || Not[RationalQ[(~n)] && GtQ[-(~d)/((~b)*(~c) - (~a)*(~d)), 0]]) ? ((~a) + (~b)*(~v))^((~m) + 1)/((~b)*((~m) + 1)*((~b)/((~b)*(~c) - (~a)*(~d)))^(~n))* Hypergeometric2F1(-(~n), (~m) + 1, (~m) + 2, -(~d)*((~a) + (~b)*(~v))/((~b)*(~c) - (~a)*(~d))) : nothing) #1_1_1_2_38
#     :(@rule ∫(((~a) + (~!b)*(~v))^(~m)*((~c) + (~!d)*(~v))^(~n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m), (~n)) && !isequal((~b)*(~c) - (~a)*(~d), 0) && Not[IntegerQ[(~m)]] && Not[IntegerQ[(~n)]] && (RationalQ[(~m)] || Not[SimplerQ[(~n) + 1, (~m) + 1]]) ? ((~c) + (~d)*(~v))^ FracPart( (~n))/(((~b)/((~b)*(~c) - (~a)*(~d)))^IntPart((~n))*((~b)*((~c) + (~d)*(~v))/((~b)*(~c) - (~a)*(~d)))^ FracPart((~n)))* Int(((~a) + (~b)*(~v))^(~m)*Simp((~b)*(~c)/((~b)*(~c) - (~a)*(~d)) + (~b)*(~d)*(~v)/((~b)*(~c) - (~a)*(~d)), (~v))^(~n), (~v)) : nothing) #1_1_1_2_39
#     :(@rule ∫(((~!a) + (~!b)*(~u))^(~!m)*((~!c) + (~!d)*(~u))^(~!n),(~v)) => !contains_int_var(~v, (~a), (~b), (~c), (~d), (~m), (~n)) && linear_expansion((~u), x)[3] && !isequal(Coefficient[(~u), x, 0], 0) ? 1/Coefficient((~u), (~v), 1)* Subst(Int(((~a) + (~b)*(~v))^(~m)*((~c) + (~d)*(~v))^(~n), (~v)), (~v), (~u)) : nothing) #1_1_1_2_40
# # (* IntLinearQ[a,b,c,d,m,n,x] returns True iff (a+b*x)^m*(c+d*x)^n is  integrable wrt x in terms of non-hypergeometric functions. *) IntLinearQ[a_, b_, c_, d_, m_, n_, x_] := IGtQ[m, 0] || IGtQ[n, 0] || IntegersQ[3*m, 3*n] || IntegersQ[4*m, 4*n] || IntegersQ[2*m, 6*n] || IntegersQ[6*m, 2*n] || ILtQ[m + n, -1] || IntegerQ[m + n] && RationalQ[m] 
]